{% set name = "pint-xarray" %}
{% set version = "0.5.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f3c6deb290a8e10daec610ae6587cf29fd9051f9017d3f3745a3f4d10146de4f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
    - setuptools_scm >=7.0
  run:
    - numpy >=1.17
    - pint >=0.16
    - python >={{ python_min }}
    - xarray >=0.16.1

test:
  imports:
    - pint_xarray
    - pint_xarray.tests
  commands:
    - pip check
    - python -c 'from pint_xarray import __version__; assert __version__ != "0.0.0"'
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/xarray-contrib/pint-xarray
  summary: Physical units interface to xarray using Pint
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
    - jthielen
